
package Formularios;

import java.awt.Color;


public class dialogAyuda extends javax.swing.JDialog {

    public dialogAyuda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lblTitulo.setBackground(Color.black);
        lblTitulo.setForeground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        PanelInstrucciones = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtareaPreparar = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("COMO JUGAR?");
        lblTitulo.setFocusable(false);
        lblTitulo.setOpaque(true);
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 57));

        PanelInstrucciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtareaPreparar.setEditable(false);
        txtareaPreparar.setColumns(20);
        txtareaPreparar.setLineWrap(true);
        txtareaPreparar.setRows(5);
        txtareaPreparar.setText("PREPARACION:\nAntes de empezar a jugar, tendremos que tener lista nuestro archivo en formato (.txt) que contendra nuestra cantidad de palabras  necesarias segun la difucultad en la que juguemos; En el archivo debe de haber una palabra por linea para leerse correctamente.\n\nLas cantidad de palabras estan dadas por dificultad de manera que: \n-> Facil: 4 Palabras.\n-> Normal: 8 Palabras\n-> Dificl: 12 Palabras.\n\nEntonces en el archivo debe de haber minimo 12 palabras.\n\nINSTRUCCIONES:\nCada casilla tiene una palabra oculta, y cada casilla tiene a su pareja con la misma palabra, debes descubrir todas las casillas pares si quieres ganar, intenta descubrirlas todas en la menor cantidad de fallos posibles, suerte!\n\n");
        txtareaPreparar.setWrapStyleWord(true);
        txtareaPreparar.setOpaque(false);
        jScrollPane2.setViewportView(txtareaPreparar);

        PanelInstrucciones.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 340, 402));

        getContentPane().add(PanelInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 69, 350, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dialogAyuda dialog = new dialogAyuda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelInstrucciones;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txtareaPreparar;
    // End of variables declaration//GEN-END:variables
}
